
pipeline {
    agent any  // Use any available agent

    tools {
        maven 'Maven'  // Ensure this matches the name configured in Jenkins
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/narasimhaa44/Devopsf1.git'
            }
        }

        stage('Build') {
            steps {
                dir('mavselpipe'){
                  sh 'mvn clean package'  // Run Maven build
                }
            }
        }

        stage('Test') {
            steps {
                  dir('mavselpipe'){
                      sh 'mvn test'  // Run unit tests
                }
            }
        }

        stage('Run Application') {
            steps {
                dir('mavselpipe') {
                    sh 'mvn exec:java -Dexec.mainClass="com.example.App"'
                }
            }
        }

        
    }

    post {
        success {
            echo 'Build and deployment successful!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}
