pipeline {
	agent any
	 
	 tools {
	 	gradle 'Gradle'
	 }
	 
	 stages {
	 	
	 	stage('Check-out') {
	 		steps {
	 			git branch :'main' , url :'https://github.com/narasimhaa44/devopsf1.git'
	 		}
	 	}
	 	
	 	stage('Build') {
	 		steps {
	 			dir('mygradpipe') {
	 				sh 'gradle build'
	 			}
	 		}
	 	}
	 	
	 	stage('Run application') {
	 		steps {
	 			dir('mygradpipe') {
	 				sh 'gradle run'
	 			}
	 		}
	 	}
	 	
	 	}
	 	post {
	 		success {
	 			echo 'Gralde Ec=xecuted succesfully'
	 		}
	 		failure {
	 			echo 'Gradle not executed'
	 		}	
	 	}
	 }
	 	
